#!/bin/sh
# Rudimentary initd script

# You will need to change these to your match your environment
prog=/root/funky_log_seer/Client/LogObserver.py
logfiles=/root/funky_log_seer/Client/logfiles

start() {
    echo -n $"Starting $prog: "
    python $prog "$logfiles"
}

case $1 in
    start)
        start
    ;;
    *)

    echo $"Usage: $prog {start}"
    exit 3
esac

exit 0
